version: "3.3"

services:

  apache:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./html/:/var/www/html/
    container_name: "apache"
    depends_on:
      - php
  php:
    image: php:8.1-fpm
    container_name: "php"
    volumes:
      - ./web:/usr/local/apache2/htdocs
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    container_name: "mysql"
    depends_on:
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:8080"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    container_name: "phpmyadmin"

networks:
    default:
        driver: bridge
      
