version: '2.12'

services:
  Sidamon:
    image: httpd:latest
    container_name: Sidamon
    ports:
      - 8080:80
    restart: always
    
  php:
    image: php:latest
    container_name: php
    restart: always
    depends_on:
      - Sidamon
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 80:8080
    restart: always
    depends_on:
      - mariadb
      
  mariadb:
    image: mysql:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: sidamon
      MYSQL_USER: sidamon
      MYSQL_PASSWORD: password
    depends_on:
      - php
      
  node.js:
    image: node:latest
    container_name: node.js
    restart: always

network_mode: "bridge"
      