version: "3.3"

services:

  php:
    image: php:latest
    volumes:
      - ./html/:/var/www/html/
    container_name: "php"

  apache:
    image: httpd:latest
    depends_on:
      - php
      - mariadb
    ports:
      - "80:80"
    volumes:
      - ./html/:/var/www/html/
    container_name: "apache"

  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Sio2021-2023"
      MYSQL_DATABASE: "sidamon"
      MYSQL_USER: "sidamon"
      MYSQL_PASSWORD: "password"
    container_name: "mariadb"

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always
    container_name: "adminer"

networks:
    default:
        driver: bridge
      
